version: "3.7"
# Sources
#   - Docker Hub Mongo https://hub.docker.com/_/mongo
#   - Docker Compose tutorial https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-docker-compose
services:
  # web:
    # build: .
    # ports:
      # - "5000:5000"
    # volumes:
      # - .:/code
    # environment:
      # FLASK_ENV: development
  mongo:
    image: "mongo:4.4"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    volumes:
      - /var/lib/mongdb/data/db:/data/db