version: "3.7"
# Sources
#   - Docker Hub Mongo https://hub.docker.com/_/mongo
#   - Docker Compose tutorial https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-docker-compose
#   - Docker Hub Mongo-Express https://hub.docker.com/_/mongo-express
#   - Mongo Auth https://medium.com/rahasak/enable-mongodb-authentication-with-docker-1b9f7d405a94
#   - Node js compose tutorial https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose-es#paso-1-clonar-el-proyecto-y-modificar-las-dependencias
services:
  mean-store-graphql-api:
    image: nodejs:10.23.1-alpine3.9
    container_name: graphql
    restart: unless-stopped
    ports:
      - "80:4200"
    environment:
      - MEAN_STORE_NODE_ENV="production"
      - MEAN_STORE_SECRET
      - MEAN_STORE_PORT
      - MEAN_STORE_DATABASE
    networks:
      - mean-store-network
    depends_on:
      - mongo
    working_dir: /home/node/app
    volumes:
      - ../mean-graphql-api:/home/node/app
    command:
      - ./wait-for.sh 127.0.0.1:27017 && npm i && npm start

  mongo:
    image: "mongo:4.4"
    restart: always
    command: [--auth]
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - /var/lib/mongodb/data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - mean-store-network

networks:
  app-network:
    driver: bridge