version: "3.7"
# Sources
#   - Docker Hub Mongo https://hub.docker.com/_/mongo
#   - Docker Compose tutorial https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-docker-compose
#   - Docker Hub Mongo-Express https://hub.docker.com/_/mongo-express
services:
  # web:
    # build: .
    # ports:
      # - "5000:5000"
    # volumes:
      # - .:/code
    # environment:
      # FLASK_ENV: development
  mongo:
    image: "mongo:4.4"
    restart: always
    command: [--auth]
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - /var/lib/mongodb/data/db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    volumes:
      - /var/lib/mongodb/data/express:/data/db